//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "guild_configs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guild_id: String,
    pub channel_id: Option<String>,
    pub report_interval: i64,
    pub threshold: i64,
    pub enabled: bool,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sent_alerts::Entity")]
    SentAlerts,
    #[sea_orm(has_many = "super::user_reports::Entity")]
    UserReports,
}

impl Related<super::sent_alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SentAlerts.def()
    }
}

impl Related<super::user_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserReports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
