//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "incidents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    pub impact: String,
    pub status: String,
    pub started_at: DateTimeUtc,
    pub resolved_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::incident_updates::Entity")]
    IncidentUpdates,
}

impl Related<super::incident_updates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IncidentUpdates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
