//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "incident_updates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub incident_id: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub status: String,
    pub published_at: DateTimeUtc,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::IncidentId",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Incidents,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
