//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sent_alerts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_sent_alerts_lookup")]
    pub guild_id: Option<String>,
    #[sea_orm(unique_key = "idx_sent_alerts_lookup")]
    pub user_id: Option<String>,
    #[sea_orm(unique_key = "idx_sent_alerts_lookup")]
    pub alert_type: String,
    #[sea_orm(unique_key = "idx_sent_alerts_lookup")]
    pub reference_id: String,
    pub notified_at: DateTimeUtc,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
