//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "status_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub indicator: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(unique)]
    pub source_timestamp: DateTimeUtc,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
