//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user_reports")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub guild_id: String,
    pub user_id: String,
    pub incident_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub status: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guild_configs::Entity",
        from = "Column::GuildId",
        to = "super::guild_configs::Column::GuildId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GuildConfigs,
}

impl Related<super::guild_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildConfigs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
