//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "command_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub command_name: String,
    pub subcommand: Option<String>,
    pub user_id: String,
    pub guild_id: Option<String>,
    pub channel_id: Option<String>,
    pub executed_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
